<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Load the main JS entry point via Vite -->
        @vite('resources/js/app.js')
        <!-- Inertia directive to inject dynamic tags into the document <head> -->
        @inertiaHead
    </head>
    <body>
        <!-- Mounting point automatically generated by Inertia (creates a div with id="app" containing page data) -->
        @inertia
    </body>
</html>